apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-staging-new
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: test
spec:
  project: default
  destination:
    name: in-cluster
    namespace: test-staging
  source:
    path: resources-staging
    repoURL: https://github.com/bogdan-volynets/guestbook-local.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
