apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  labels:
    codefresh.io/product: my-product
spec:
  project: default
  source:
    path: manifests/trio-app/aperture-dev
    repoURL: https://github.com/aperture-sci/DevOps
    targetRevision: main
  destination:
    name: in-cluster
    namespace: eti-local-runtime0105
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
