apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-staging-local
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  labels:
    codefresh.io/product: four
    testing: four
  annotations:
    codefresh.io/product: conflict
spec:
  project: default
  source:
    path: resources-staging
    repoURL: https://github.com/bogdan-volynets/guestbook-local
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: test-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=true
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
